on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        pip install -r requirements.txt
        pytest

    - name: Run example
      env:
        BACKUPS_FILE: example/backups.yaml
        BACKUPS_DB_PASSWORD: ${{ secrets.BACKUPS_DB_PASSWORD }}
        BACKUPS_ZIP_PASSWORD: ${{ secrets.BACKUPS_ZIP_PASSWORD }}
        BACKUPS_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "==> backups --version"
        backups version

        echo "==> backups ls"
        backups ls

        echo "==> backups show acme"
        backups show acme

    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
